# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(879, 585)
        self.field_text = QtWidgets.QTextEdit(parent=Form)
        self.field_text.setGeometry(QtCore.QRect(13, 10, 541, 561))
        self.field_text.setObjectName("field_text")
        self.list_notes = QtWidgets.QListWidget(parent=Form)
        self.list_notes.setGeometry(QtCore.QRect(570, 20, 291, 191))
        self.list_notes.setObjectName("list_notes")
        self.list_notes_label = QtWidgets.QLabel(parent=Form)
        self.list_notes_label.setGeometry(QtCore.QRect(570, 0, 91, 16))
        self.list_notes_label.setObjectName("list_notes_label")
        self.button_note_del = QtWidgets.QPushButton(parent=Form)
        self.button_note_del.setGeometry(QtCore.QRect(720, 220, 141, 23))
        self.button_note_del.setObjectName("button_note_del")
        self.button_note_create = QtWidgets.QPushButton(parent=Form)
        self.button_note_create.setGeometry(QtCore.QRect(570, 220, 141, 23))
        self.button_note_create.setObjectName("button_note_create")
        self.button_note_save = QtWidgets.QPushButton(parent=Form)
        self.button_note_save.setGeometry(QtCore.QRect(570, 250, 291, 23))
        self.button_note_save.setObjectName("button_note_save")
        self.list_tags_label = QtWidgets.QLabel(parent=Form)
        self.list_tags_label.setGeometry(QtCore.QRect(570, 290, 71, 16))
        self.list_tags_label.setObjectName("list_tags_label")
        self.list_tags = QtWidgets.QListWidget(parent=Form)
        self.list_tags.setGeometry(QtCore.QRect(570, 310, 291, 192))
        self.list_tags.setObjectName("list_tags")
        self.field_tag = QtWidgets.QLineEdit(parent=Form)
        self.field_tag.setGeometry(QtCore.QRect(570, 510, 291, 20))
        self.field_tag.setObjectName("field_tag")
        self.button_tag_add = QtWidgets.QPushButton(parent=Form)
        self.button_tag_add.setGeometry(QtCore.QRect(570, 540, 141, 23))
        self.button_tag_add.setObjectName("button_tag_add")
        self.button_tag_del = QtWidgets.QPushButton(parent=Form)
        self.button_tag_del.setGeometry(QtCore.QRect(720, 540, 141, 23))
        self.button_tag_del.setObjectName("button_tag_del")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Умные заметки"))
        self.field_text.setPlaceholderText(_translate("Form", "Введите заметку..."))
        self.list_notes_label.setText(_translate("Form", "Список заметок"))
        self.button_note_del.setText(_translate("Form", "Удалить заметку"))
        self.button_note_create.setText(_translate("Form", "Создать заметку"))
        self.button_note_save.setText(_translate("Form", "Сохранить заметку"))
        self.list_tags_label.setText(_translate("Form", "Список тегов"))
        self.field_tag.setPlaceholderText(_translate("Form", "Введите тег..."))
        self.button_tag_add.setText(_translate("Form", "Добавить к заметке"))
        self.button_tag_del.setText(_translate("Form", "Открепить от заметки"))
